"""Write and append markdown transcripts."""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path

from hearsay.output.formatter import clean_transcript_text, format_timestamp, make_title
from hearsay.transcription.engine import TranscriptionResult

log = logging.getLogger(__name__)

_FOOTER_MARKER = "\n---\n"
_TS_LINE_RE = re.compile(r"^(\[\d+:\d+(?::\d+)?\] )(.+?)\ *$")


class MarkdownWriter:
    """Writes transcript results to a .md file, appending as chunks arrive."""

    def __init__(self, output_dir: str | Path, title: str | None = None) -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.title = title or make_title()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.file_path = self.output_dir / f"transcript_{timestamp}.md"
        self._header_written = False
        self._language: str = "en"

    def _write_header(self) -> None:
        with open(self.file_path, "w", encoding="utf-8") as f:
            f.write(f"# {self.title}\n\n")
        self._header_written = True
        log.info("Transcript file created: %s", self.file_path)

    def append(self, result: TranscriptionResult) -> None:
        """Append a transcription result as timestamped lines matching the live view."""
        if not self._header_written:
            self._write_header()

        self._language = result.language or self._language

        if not result.segments:
            self._append_fallback(result)
            return

        chunk_offset = result.start_time
        lines: list[str] = []
        for seg in result.segments:
            seg_text = seg["text"].strip()
            if not seg_text:
                continue
            ts = format_timestamp(chunk_offset + seg["start"])
            lines.append(f"[{ts}] {seg_text}  \n")

        if lines:
            with open(self.file_path, "a", encoding="utf-8") as f:
                f.write("".join(lines))

        log.debug("Appended chunk %d to %s", result.chunk_index, self.file_path)

    def _append_fallback(self, result: TranscriptionResult) -> None:
        """Fallback for results with empty segments (e.g. after dedup)."""
        text = result.text.strip()
        if not text:
            return
        ts = format_timestamp(result.start_time)
        with open(self.file_path, "a", encoding="utf-8") as f:
            f.write(f"[{ts}] {text}  \n")

    def finalize(self, total_duration: float | None = None) -> Path:
        """Write a footer and return the file path."""
        if not self._header_written:
            self._write_header()

        with open(self.file_path, "a", encoding="utf-8") as f:
            f.write("\n---\n\n")
            f.write(f"*Generated by Hearsay on {datetime.now():%Y-%m-%d at %H:%M}*\n")
            if total_duration:
                from hearsay.output.formatter import format_duration
                f.write(f"*Recording duration: {format_duration(total_duration)}*\n")

        log.info("Transcript finalized: %s", self.file_path)
        return self.file_path

    def post_process(self) -> None:
        """Clean up the text portion of each timestamped line, preserving timestamps."""
        if not self.file_path.exists():
            return

        content = self.file_path.read_text(encoding="utf-8")
        footer_idx = content.rfind(_FOOTER_MARKER)
        if footer_idx == -1:
            log.warning("No footer marker found, skipping post-processing")
            return

        header_end = content.index("\n\n") + 2
        header = content[:header_end]
        body = content[header_end:footer_idx]
        footer = content[footer_idx:]

        cleaned_lines: list[str] = []
        for line in body.splitlines(keepends=True):
            m = _TS_LINE_RE.match(line.rstrip("\n"))
            if m:
                ts_prefix, text = m.group(1), m.group(2)
                text = clean_transcript_text(text, language=self._language)
                cleaned_lines.append(f"{ts_prefix}{text}  \n")
            else:
                cleaned_lines.append(line)

        self.file_path.write_text(
            header + "".join(cleaned_lines) + footer,
            encoding="utf-8",
        )
        log.info("Post-processed transcript: %s", self.file_path)
