"""Write and append markdown transcripts."""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from hearsay.constants import CHUNK_DURATION_S
from hearsay.output.formatter import format_timestamp, make_title
from hearsay.transcription.engine import TranscriptionResult

log = logging.getLogger(__name__)


class MarkdownWriter:
    """Writes transcript results to a .md file, appending as chunks arrive."""

    def __init__(self, output_dir: str | Path, title: str | None = None) -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.title = title or make_title()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.file_path = self.output_dir / f"transcript_{timestamp}.md"
        self._header_written = False

    def _write_header(self) -> None:
        """Write the markdown header on first call."""
        with open(self.file_path, "w", encoding="utf-8") as f:
            f.write(f"# {self.title}\n\n")
        self._header_written = True
        log.info("Transcript file created: %s", self.file_path)

    def append(self, result: TranscriptionResult) -> None:
        """Append a transcription result to the markdown file."""
        if not self._header_written:
            self._write_header()

        # Calculate the wall-clock offset for this chunk
        chunk_offset = result.chunk_index * CHUNK_DURATION_S

        with open(self.file_path, "a", encoding="utf-8") as f:
            if result.segments:
                for seg in result.segments:
                    abs_start = chunk_offset + seg["start"]
                    ts = format_timestamp(abs_start)
                    f.write(f"**[{ts}]** {seg['text']}\n\n")
            else:
                ts = format_timestamp(chunk_offset)
                f.write(f"**[{ts}]** {result.text}\n\n")

        log.debug("Appended chunk %d to %s", result.chunk_index, self.file_path)

    def finalize(self, total_duration: float | None = None) -> Path:
        """Write a footer and return the file path."""
        if not self._header_written:
            self._write_header()

        with open(self.file_path, "a", encoding="utf-8") as f:
            f.write("---\n\n")
            f.write(f"*Generated by Hearsay on {datetime.now():%Y-%m-%d at %H:%M}*\n")
            if total_duration:
                from hearsay.output.formatter import format_duration
                f.write(f"*Recording duration: {format_duration(total_duration)}*\n")

        log.info("Transcript finalized: %s", self.file_path)
        return self.file_path
