"""Write and append markdown transcripts."""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from hearsay.constants import PARAGRAPH_GAP_S
from hearsay.output.formatter import clean_transcript_text, make_title
from hearsay.transcription.engine import TranscriptionResult

log = logging.getLogger(__name__)

# Markers used to split header / body / footer for post-processing
_FOOTER_MARKER = "\n---\n"


class MarkdownWriter:
    """Writes transcript results to a .md file, appending as chunks arrive."""

    def __init__(self, output_dir: str | Path, title: str | None = None) -> None:
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.title = title or make_title()
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.file_path = self.output_dir / f"transcript_{timestamp}.md"
        self._header_written = False

        # Track absolute timing across chunks for gap-based paragraph breaks
        self._last_segment_end: float | None = None
        self._language: str = "en"

    def _write_header(self) -> None:
        """Write the markdown header on first call."""
        with open(self.file_path, "w", encoding="utf-8") as f:
            f.write(f"# {self.title}\n\n")
        self._header_written = True
        log.info("Transcript file created: %s", self.file_path)

    def append(self, result: TranscriptionResult) -> None:
        """Append a transcription result using segment-level gap detection."""
        if not self._header_written:
            self._write_header()

        self._language = result.language or self._language

        if not result.segments:
            self._append_fallback(result)
            return

        chunk_offset = result.chunk_index * 30  # seconds offset for this chunk
        pieces: list[str] = []

        for seg in result.segments:
            seg_start = chunk_offset + seg["start"]
            seg_text = seg["text"].strip()
            if not seg_text:
                continue

            # Determine separator: paragraph break on long gap, space otherwise
            if self._last_segment_end is not None:
                gap = seg_start - self._last_segment_end
                if gap >= PARAGRAPH_GAP_S:
                    pieces.append("\n\n")
                else:
                    pieces.append(" ")
            # else: very first segment, no separator needed

            pieces.append(seg_text)
            self._last_segment_end = chunk_offset + seg["end"]

        if pieces:
            with open(self.file_path, "a", encoding="utf-8") as f:
                f.write("".join(pieces))

        log.debug("Appended chunk %d to %s", result.chunk_index, self.file_path)

    def _append_fallback(self, result: TranscriptionResult) -> None:
        """Fallback for results with empty segments (e.g. after dedup)."""
        text = result.text.strip()
        if not text:
            return
        with open(self.file_path, "a", encoding="utf-8") as f:
            if self._last_segment_end is not None:
                f.write(" ")
            f.write(text)

    def finalize(self, total_duration: float | None = None) -> Path:
        """Write a footer and return the file path."""
        if not self._header_written:
            self._write_header()

        with open(self.file_path, "a", encoding="utf-8") as f:
            f.write("\n\n---\n\n")
            f.write(f"*Generated by Hearsay on {datetime.now():%Y-%m-%d at %H:%M}*\n")
            if total_duration:
                from hearsay.output.formatter import format_duration
                f.write(f"*Recording duration: {format_duration(total_duration)}*\n")

        log.info("Transcript finalized: %s", self.file_path)
        return self.file_path

    def post_process(self) -> None:
        """Read the finalized transcript, clean up the body, and rewrite."""
        if not self.file_path.exists():
            return

        content = self.file_path.read_text(encoding="utf-8")

        # Split into header, body, footer using the --- marker
        footer_idx = content.rfind(_FOOTER_MARKER)
        if footer_idx == -1:
            log.warning("No footer marker found, skipping post-processing")
            return

        # Header ends at first double newline after the title line
        header_end = content.index("\n\n") + 2
        header = content[:header_end]
        body = content[header_end:footer_idx]
        footer = content[footer_idx:]

        cleaned = clean_transcript_text(body, language=self._language)

        self.file_path.write_text(
            header + cleaned + footer,
            encoding="utf-8",
        )
        log.info("Post-processed transcript: %s", self.file_path)
